apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app
  labels:
    app: trend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend
  template:
    metadata:
      labels:
        app: trend
    spec:
      containers:
        - name: trend
          image: sarwanragul/trend-app:latest
          ports:
            - containerPort: 3000

